# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install node.js and run tests across stable and nightly builds on Windows, Ubuntu and macOS.

name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        node-version: [16.20.2]
        os: [ubuntu-latest]

    steps:
      - name: Setup Repo
        uses: actions/checkout@v2

      - name: Uses node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }} # tests across multiple node.js versions

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Format-Check
        run: yarn format-check

      - name: Compile
        run: yarn compile

      - name: Test
        run: yarn test
